name: test renovate
on:
  push:
    branches:
      - master


jobs:
  renovate:
    runs-on: ubuntu-latest

    env:
      RENOVATE_CONSTRAINTS: '{"python": "3.6"}'
      RENOVATE_CONSTRAINTS_FILTERING: "strict"    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # You can adjust the Node.js version as needed

      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        run: renovate
