name: test renovate
on:
  push:
    branches:
      - master


jobs:
  renovate:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/renovatebot/renovate:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Run Your Commands
        run: |
           renovate fazizsoltani/renovate-test