name: test renovate
on:
  push:
    branches:
      - master


jobs:
  renovate:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/renovatebot/renovate:latest

    steps:
      - name: Checkout Repository
        run: git checkout $GITHUB_REF

      - name: Run Your Commands
        run: |
           renovate fazizsoltani/renovate-test